:page-nav-title: Backend design
:page-parent: architecture::design
:page-title: The backend design for Pledger.io
:page-section: architecture
:page-layout: section
:page-order: 2
:page-status: published

ifndef::document-root[:document-root: ../../]
include::../../_document-setup.adoc[]

The REST-api is the main component of the application.
This part of {application} is build using the following tooling:

- link:https://gradle.org/[Gradle],
used as the build tool.
- link:https://micronaut.io/[Micronaut framework],
used as the DI and API framework.
- link:https://docs.langchain4j.dev/[LangChain4j],
used as the engine to interact with Vector stores and LLM implementations.

== Rest design

The REST interface is designed contract-first.
This means that all APIs are designed in an Open API Specification file and interfaces are generated using Micronaut.

The code is generated at compile time, and each module implements a small part of the REST interface.

== Internal design

=== Modular design

The REST-api is designed to be a stateless application.
The application is split up in several modules, where each module can depend on other modules.
This is done to allow the application to be designed around a use case, like personal budgeting or small organizations.

[%header,cols="1,1,2"]
|===

|*Module*|*Dependencies*|*Description*

|Core
|-
|The base module for the entire {application} application.


|Banking
a|
- Core
|The module contains all logic regarding the transaction management and account management.

|Classification
a|
- Core
- Banking
|Contains a system to categorize things in {application}.

|Budget
a|
- Core
- Banking
|Contains the logic allowing users to budget their spending.

|Contract
a|
- Core
- Banking
|Contains the logic allowing users to manage any contracts they have for spending.

|Suggestions
a|
- Core
- Banking
- Classification
- Budget
|Contains logic to suggest changes to transactions, either using pre-defined rules or AI.

|Exporter
a|
- Core
- Banking
- Classification
- Budget
|Contains the logic to import and export all information from a users account.

|===

=== Architecture of each module

Each of the modules is setup using the following layered architecture:

[plantuml, generated/architecture/layer-architecture, svg]
....
@startuml
title Pledger.io Layer Design

package generated {
[API Interface] <<..finance.rest..>> as api_interface #Orange/PowderBlue
}

package domain {
[Database] <<..finance..domain.jpa..>> as jpa_layer #white/PowderBlue
[Commands] <<..finance..domain.commands..>> as command_layer #white/PowderBlue
[Model] <<..finance..domain.model..>> as model_layer #white/PowderBlue
[Service] <<..finance..domain.service..>> as service_layer #white/LightGray
}

package adapter {
[Internal API] <<..finance..adapter.api..>> as api_layer #white/Green
[REST API] <<..finance..adapter.rest..>> as rest_layer #white/Green
}

jpa_layer --> command_layer : listens to
jpa_layer -> model_layer : instantiates
jpa_layer -up-> api_layer : implements

model_layer --> command_layer : initiates

rest_layer --> model_layer : uses
rest_layer -> api_layer : uses
rest_layer ----> command_layer : uses

rest_layer -up-> api_interface: implements

api_layer --> model_layer : uses

service_layer -up-> api_layer : implements
service_layer -up-> model_layer : uses
service_layer -right-> command_layer : uses

api_interface ---> model_layer: uses

@enduml
....
