ifndef::document-root[:document-root: ../]
include::../_document-setup.adoc[]
:page-title: Docker
:page-parent: /installation/
:page-sort-order: 1

Running {application} using docker is an easy way to get started.
Just execute a few lines, and you are up and running.

There are several ways to get started with {application} using Docker, each one detailed below.
If you are new to Docker or are not sure as to how to use it then ask for advice.

== Supported tags

Personal Ledger uses the docker tagging system to release multiple versions.
There are various builds for various different target platforms.

Personal Ledger is currently built for:

- AMD64, under image `{docker-image}`
- ARMv8, under image `ghcr.io/pledger-io/arm64-core`

The instructions here will assume usage of the tag `latest`.
Other tags that are used are:

- `ghcr.io/pledger-io/<architecture>-core:latest`, this tag will always point to the latest release that was run
-  `ghcr.io/pledger-io/<architecture>-core:x.x.x`, these are version specific tags.

Currently, only AMD-64 and ARM64 builds are available in the official docker hub.

== Single container

These instructions will help you set up a standalone container in docker running only
{application}.
Please note that dependent images, like MySQL, are not included in this sample.
Running the single container can be useful when debugging or testing the application.

WARNING: It is advised to set up a separate container with link:https://hub.docker.com/_/mariadb[MariaDB].

=== Creating the volumes

{application} uses various storage locations in the container to store user data.
It is advised to create one volume for each of the type of storage that the application uses.

[source,shell,linenums]
....
docker volume create pledger_logs
docker volume create pledger_upload
....

=== Starting the container

You can use the command below to start the container with {application}.
Make sure to edit any environment variables to match your setup.

[source,shell,linenums,subs="attributes"]
....
 docker run -d \
         -v pledger_logs:/opt/storage/logs \
         -v pledger_uploads:/opt/storage/upload \
         -p 8080:8080 \
         --name pledger \
         -e DB_TYPE=mysql
         -e DATABASE_HOST=mariadb
         -e DATABASE_SCHEMA=pledger
         -e DATABASE_USER=pledger
         -e DATABASE_PASSWORD=pledger
         {docker-image}:latest
....

Once this command is run a docker container with {application} will start, this may take some time when run the first time.
The application will automatically attempt to update the database to the version running.
After {application} is started you can access the interface using:

> http://localhost:8080

== Docker compose

"Docker-compose" is a tool that can be used to bundle multiple containers into one single deployment.
When managing the images and volumes needed for {application} this method is preferred rather than single container runs.

=== Create a compose file

A compose file describes how the deployment of the various images should happen.
To be able to deploy Personal Ledger you can use the compose file below as a template.

[source,yaml,linenums,subs="attributes"]
....
version: '3.7'
services:

    pledger:
      container_name: pledger
      image: {docker-image}
      ports:
        - "80:8080"
      restart: unless-stopped
      environment:
        - DB_TYPE=mysql
        - DATABASE_HOST=pledger_db
        - DATABASE_SCHEMA=pledger
        - DATABASE_USER=pledger
        - DATABASE_PASSWORD=pledger
      volumes:
        - "pledger_logs:/opt/storage/logs"
        - "pledger_uploads:/opt/storage/upload"
    pledger_db:
      container_name: pledger_db
      image: mysql
      args: ["--default-authentication-plugin=mysql_native_password"]
      volumes:
        - "pledger_db:/var/lib/mysql"
      environment:
        - MYSQL_ROOT_PASSWORD=secret
        - MYSQL_DATABASE=pledger
        - MYSQL_USER=pledger
        - MYSQL_PASSWORD=pledger

volumes:
  pledger_logs:
  pledger_uploads:
  pledger_db:
....

=== Starting the deployment

Once the compose file is created you can start the deployment using the command below.

[source,shell,linenums]
....
docker-compose up -d
....

TIP: This command should be run in the same directory as the compose file.

This will start the deployment in the background.
You can check the status of the deployment using the command below.

[source,shell,linenums]
....
docker-compose ps
....

This will show the status of the deployment for each of the containers.